/**
 * The basenames (no `.png`) of every icon in `apps/web/public/art/icons/` —
 * the glyphs `[icon:name]` (spec 0021-1 §1d) can reference. Hardcoded
 * because that directory is served statically: `import.meta.glob` can't see
 * it, and globbing it would duplicate every file into the bundle for
 * nothing but a name list.
 *
 * Sorted with the default `Array.prototype.sort()` ordering (plain UTF-16
 * code-unit comparison — not a locale-aware `ls`, which would order
 * `arrow_N`/`arrow_NE` differently). Pinned by `noteIcons.test.ts`, which
 * reads the directory and fails loudly the moment this drifts from it.
 */
export const NOTE_ICONS: readonly string[] = [
  "arrow_E",
  "arrow_N",
  "arrow_NE",
  "arrow_NW",
  "arrow_S",
  "arrow_SE",
  "arrow_SW",
  "arrow_W",
  "beaver_archer",
  "beaver_bookshelf",
  "beaver_chainsaw",
  "beaver_chatting",
  "beaver_desk",
  "beaver_kit",
  "beaver_kyrgyz_cloth",
  "beaver_kyrgyz_rider",
  "beaver_kyrgyz_shield",
  "beaver_kyrgyz_teaching",
  "beaver_pencil",
  "beaver_pirate",
  "beaver_racecar",
  "beaver_sleeping_floating",
  "beaver_sleeping_lodge",
  "beaver_swimming",
  "book_back",
  "book_front",
  "bow",
  "chainsaw",
  "chart",
  "checkmark",
  "config",
  "dam",
  "dam_broken",
  "dam_hole_2",
  "dam_hole_3",
  "edit",
  "fire",
  "flag",
  "hearth_log",
  "kyrgyz",
  "letters",
  "lightbulb",
  "lock",
  "lock_key",
  "lock_open",
  "log_1",
  "log_2",
  "log_bite",
  "log_floating",
  "magnifying_glass",
  "next",
  "numbers",
  "pause",
  "paw",
  "pin",
  "play",
  "repeat",
  "rocket",
  "sound_off",
  "sound_on",
  "star",
  "stop",
  "stop_sign",
  "target",
  "thumbs_down",
  "thumbs_down_beaver",
  "thumbs_up",
  "thumbs_up_beaver",
  "tree",
  "tree_bite",
  "tree_stamp",
  "trophy",
  "yurt",
];
